controller_manager:
  ros__parameters:
    update_rate: 100

    teleop_controller:
      type: racecar_controllers/TeleopController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

teleop_controller:
  ros__parameters:
    drive_train_command: "current"
