joy_linux:
  ros__parameters:
    dev_name: /dev/input/js0
    
joy_teleop:
  ros__parameters:

    default:
      type: topic
      interface_type: std_msgs/msg/Float64MultiArray
      topic_name: teleop
      deadman_buttons: [4]
      axis_mappings:
        data:
          speed:
            axis: 1
            scale: 5.0
            offset: 0.0
          steering:
            axis: 3
            scale: 0.34
            offset: 0.0

  