joy_linux:
  ros__parameters:
    dev_name: /dev/input/js0
    
joy_teleop:
  ros__parameters:
    default:
      type: topic
      interface_type: std_msgs/msg/Float64MultiArray
      topic_name: teleop
      deadman_buttons: [4]
      axis_mappings:
        data:
          0: 
            axis: 1
            scale: 1.0
            offset: 0.0
          1:
            axis: 3
            scale: 1.0
            offset: 0.0

  